export const capitalize = (str: string): string => str.charAt(0).toUpperCase() + str.slice(1);
export const lowercase = (str: string): string => str.toLowerCase();
export const uppercase = (str: string): string => str.toUpperCase();
export const isString = (val: any): val is string => typeof val === 'string';
export const reverseString = (str: string): string => str.split('').reverse().join('');
export const truncate = (str: string, len: number): string => str.length > len ? str.substring(0, len) + '...' : str;
export const camelCase = (str: string): string => str.replace(/(?:^\w|[A-Z]|\b\w)/g, (w, i) => i === 0 ? w.toLowerCase() : w.toUpperCase()).replace(/\s+/g, '');
export const snakeCase = (str: string): string => str.replace(/\W+/g, ' ').split(/ |\B(?=[A-Z])/).map(w => w.toLowerCase()).join('_');
export const kebabCase = (str: string): string => str.replace(/([a-z])([A-Z])/g, '$1-$2').replace(/[\s_]+/g, '-').toLowerCase();
export const stripHtml = (html: string): string => html.replace(/<[^>]*>?/gm, '');
export const escapeHtml = (str: string): string => str.replace(/[&<>"']/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[m] as string);
export const unescapeHtml = (str: string): string => str.replace(/&amp;|&lt;|&gt;|&quot;|&#39;/g, m => ({ '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'" })[m] as string);
export const padZero = (num: number, len: number = 2): string => String(num).padStart(len, '0');
export const trimSlashes = (str: string): string => str.replace(/^\/+||\/+$/g, '');
export const countWords = (str: string): number => str.trim().split(/\s+/).length;
export const contains = (str: string, search: string): boolean => str.includes(search);
