export const isEmail = (str: string): boolean => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(str);
export const isUrl = (str: string): boolean => /^https?:\/\/[\w\-]+(\.[\w\-]+)+[/#?]?.*$/.test(str);
export const isHex = (str: string): boolean => /^[0-9A-Fa-f]+$/.test(str);
export const isHexColor = (str: string): boolean => /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/.test(str);
export const isAlpha = (str: string): boolean => /^[A-Za-z]+$/.test(str);
export const isNumeric = (str: string): boolean => /^\d+$/.test(str);
export const isAlphaNumeric = (str: string): boolean => /^[A-Za-z0-9]+$/.test(str);
export const isUuid = (str: string): boolean => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(str);
export const isIpAddress = (str: string): boolean => /^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$/.test(str);
export const isMacAddress = (str: string): boolean => /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/.test(str);
export const isPort = (str: string): boolean => { const p = parseInt(str, 10); return p > 0 && p <= 65535; };
export const isLength = (str: string, min: number, max: number): boolean => str.length >= min && str.length <= max;
export const isBase64 = (str: string): boolean => /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(str);
export const isJSON = (str: string): boolean => { try { JSON.parse(str); return true; } catch (e) { return false; } };
export const isStrongPassword = (str: string): boolean => str.length >= 8 && /[A-Z]/.test(str) && /[0-9]/.test(str) && /[^A-Za-z0-9]/.test(str);
export const isBoolean = (val: any): val is boolean => typeof val === 'boolean';
export const isSymbol = (val: any): val is symbol => typeof val === 'symbol';
export const isFunction = (val: any): val is Function => typeof val === 'function';
export const isEmptyString = (str: string): boolean => str.trim().length === 0;
export const isPostalCode = (str: string): boolean => /^\d{5}(-\d{4})?$/.test(str);
